### ISSUE TITLE
Library doesn't work properly when used in Arduino Mega 2560

### ISSUE THREAD

**Issue by nemerdaud** [arduino-libraries/ArduinoRS485#2]

**Comment by nemerdaud** [comment]
I was trying to use ArduinoModbus library that is very tied with ArduinoRS485. Using in Arduino Mega 2560, it's unable to work properly. The examples using MobBusRTUServerLed (Arduino Mega) and ModBusRTUClientToggle doen't work presenting Connection Timout in the client-side. 

If I change the Arduino Mega to another Arduino Uno, the exemple works like a charm... mas not with Mega. 

Debug a little bit de code, I could perceive that the problema was in the ArduinoRS485 library that doen't setup correctly the board pins for the Arduino Mega board. 

In the end of the RS485.cpp file, I change de instantiation of de RS485 object to:

```
#if defined(__AVR_ATmega2560__)
  RS485Class RS485(Serial1, 18, RS845_DEFAULT_DE_PIN, RS845_DEFAULT_RE_PIN);
#else
  RS485Class RS485(SERIAL_PORT_HARDWARE, RS485_DEFAULT_TX_PIN, RS845_DEFAULT_DE_PIN, RS845_DEFAULT_RE_PIN);
#endif

```
And all the communication started work great after that. 
I know I hard-coded some values, but I'm putting here just to help you guys to fix the code, if you intend to do in this way.

**Comment by per1234** [comment]
The developers of the library have decided the AVR architecture of the Arduino Mega 2560 will not be supported: https://github.com/arduino-libraries/ArduinoRS485/pull/35
