### ISSUE TITLE
Probable error in end function

### ISSUE THREAD

**Issue by fra87** [arduino-libraries/ArduinoRS485#29]
Hello

While debugging an (unrelated) issue I had a look at the source code of the library and found this in the `end` function in RS485.cpp (line 75 and following):

```
  if (_rePin > -1) {
    digitalWrite(_rePin, LOW);
    pinMode(_dePin, INPUT);
  }
  
  if (_dePin > -1) {
    digitalWrite(_dePin, LOW);
    pinMode(_rePin, INPUT);
  }
```

I think the `_dePin` and `_rePin` in the pinMode functions are swapped.

I assume this is not a real issue, since not a lot of people would use the end function, but for completeness sake maybe it is to fix

**Comment by facchinm** [comment]
Hi @fra87 ,
thank you for finding the bug! Could you also submit a PR so we can give you proper attribution for the fix? Thanks!

**Comment by fra87** [comment]
Hello @facchinm
Sure, I just submitted  PR #33 solving this issue

Best regards
