### ISSUE TITLE
Compatible with raspberry pico ?

### ISSUE THREAD

**Issue by SebMoy** [arduino-libraries/ArduinoRS485#37]
Hello,

I would like use the ArduinoModbus with the raspberry pico.
But during the compilation, the errors appear.

`Indexing .pio/build/pico/libFrameworkArduino.a
In file included from .pio/libdeps/pico/ArduinoRS485/src/RS485.cpp:20:
.pio/libdeps/pico/ArduinoRS485/src/RS485.h:44:30: error: 'A6' was not declared in this scope; did you mean 'A3'?
   44 | #define RS485_DEFAULT_DE_PIN A6
      |                              ^~
.pio/libdeps/pico/ArduinoRS485/src/RS485.cpp:204:62: note: in expansion of macro 'RS485_DEFAULT_DE_PIN'
  204 | RS485Class RS485(SERIAL_PORT_HARDWARE, RS485_DEFAULT_TX_PIN, RS485_DEFAULT_DE_PIN, RS485_DEFAULT_RE_PIN);
      |                                                              ^~~~~~~~~~~~~~~~~~~~
.pio/libdeps/pico/ArduinoRS485/src/RS485.h:45:30: error: 'A5' was not declared in this scope; did you mean 'A3'?
   45 | #define RS485_DEFAULT_RE_PIN A5
      |                              ^~
.pio/libdeps/pico/ArduinoRS485/src/RS485.cpp:204:84: note: in expansion of macro 'RS485_DEFAULT_RE_PIN'
  204 | RS485Class RS485(SERIAL_PORT_HARDWARE, RS485_DEFAULT_TX_PIN, RS485_DEFAULT_DE_PIN, RS485_DEFAULT_RE_PIN);
      |                                                                                    ^~~~~~~~~~~~~~~~~~~~
*** [.pio/build/pico/libcb1/ArduinoRS485/RS485.cpp.o] Error 1`

can it be used with a raspberry ?

Thank you.

**Comment by per1234** [comment]
Hi @SebMoy. The library is [only compatible with boards of the `samd`, `mbed_portenta`, and `mbed_opta` architectures](https://github.com/arduino-libraries/ArduinoRS485/blob/d7aca5249ccdf7b16bd5d4af0b4022ed5195ba65/library.properties#L9). Use with the Raspberry Pi Pico board is not supported.

Check the 3rd party RS-485 libraries available from [the PlatformIO Registry](https://registry.platformio.org/) to see if the Arduino community provides a more comprehensive library.

**Comment by facchinm** [comment]
What @per1234 said if of cource right, but you can safely compile it once you replace [these lines](https://github.com/arduino-libraries/ArduinoRS485/blob/master/src/RS485.h#L44-L45) with some pins that actually exist on RP2040

**Comment by SebMoy** [comment]
Thank you for answer
