### ISSUE TITLE
Raspberry pi pico w issue

### ISSUE THREAD

**Issue by sergioguimaraes** [arduino-libraries/ArduinoRS485#38]
Looks like this library is not compatible with raspberry pi pico w, since it is generating errors during compiling.

**Comment by per1234** [comment]
Hi @sergioguimaraes. The project managers have decided that the library does not officially support the architecture of the RP2040 boards such as the RPi Pico W at this time (see https://github.com/arduino-libraries/ArduinoRS485/issues/37).

One of the developers has provided a hint about how the user may modify the library code to make it compatible here:

https://github.com/arduino-libraries/ArduinoRS485/issues/37#issuecomment-1381481760

If you give that a try and have any troubles, please feel free to request assistance on the Arduino Forum:

https://forum.arduino.cc/

We'll surely be able to help you out over there.
