### ISSUE TITLE
Як редагувати код для заливки на AVR якщо стоїть блок як його знайти на змінити ?

### ISSUE THREAD

**Issue by Valentin2228** [arduino-libraries/ArduinoRS485#55]
Потрібно змінити ціни через код та залити в ATmega64a. Та в коді стоїть блок . Як його знайти та змінити ? Автор коду поїхав в іншу країну та не виходить на зв'язок .

**Comment by per1234** [comment]
Hi @Valentin2228. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
